// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB77VT0fKtIG-J1aR86xnH4sjZ5SnIfnAo',
    appId: '1:814069705040:web:ed35ad02bbf8ec5da62455',
    messagingSenderId: '814069705040',
    projectId: 'karunakar-7daa8',
    authDomain: 'karunakar-7daa8.firebaseapp.com',
    storageBucket: 'karunakar-7daa8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwSx0GagTQRqxypwITT8Sx3vsOmJ-IINo',
    appId: '1:814069705040:android:888d520b2c30d62da62455',
    messagingSenderId: '814069705040',
    projectId: 'karunakar-7daa8',
    storageBucket: 'karunakar-7daa8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJn_qDa-568JTI0TuyIaXhgVnffUxZ_e8',
    appId: '1:814069705040:ios:3cf5498b468503fea62455',
    messagingSenderId: '814069705040',
    projectId: 'karunakar-7daa8',
    storageBucket: 'karunakar-7daa8.firebasestorage.app',
    iosBundleId: 'com.example.snackHackApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJn_qDa-568JTI0TuyIaXhgVnffUxZ_e8',
    appId: '1:814069705040:ios:3cf5498b468503fea62455',
    messagingSenderId: '814069705040',
    projectId: 'karunakar-7daa8',
    storageBucket: 'karunakar-7daa8.firebasestorage.app',
    iosBundleId: 'com.example.snackHackApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKqo1GSfAq-4C_XYwOLpZM61kjETIEyUk',
    appId: '1:814069705040:web:449eab22723186caa62455',
    messagingSenderId: '814069705040',
    projectId: 'karunakar-7daa8',
    authDomain: 'karunakar-7daa8.firebaseapp.com',
    storageBucket: 'karunakar-7daa8.firebasestorage.app',
  );
}
